### PR TITLE
9.0 release fixes

### LINKED ISSUE #103: [BUG] Rocky Linux 9.0 - Release Issue
**Describe the bug**
To make it a bit easier this time, this should be the tracking issue for all general 9.0 release issues.

**Expected behavior**
There should not be any missing needles, or other unexpected behavior through the tests.

Use this issue if you have any changes related to the 9.0 release.
Any specific issues which should be tracked can still get their own Issue though, reference this one here to make sure all can be easily tracked!

### PR DESCRIPTION
**Pull request by akatch**
# Description
This branch contains the fixes developed for testing of the 9.0 release.

Fixes #103 

# How Has This Been Tested?

```
openqa-cli api -X POST isos ISO=Rocky-9.0-x86_64-dvd.iso ARCH=x86_64 DISTRI=rocky FLAVOR=universal VERSION=9.0 BUILD=-$(date +%Y%m%d.%H%M%S).0-universal-$(git branch --show-current)
openqa-cli api -X POST isos ISO=Rocky-9.0-x86_64-dvd.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=9.0 BUILD=-$(date +%Y%m%d.%H%M%S).0-dvd-$(git branch --show-current)
openqa-cli api -X POST isos ISO=Rocky-9.0-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=9.0 BUILD=-$(date +%Y%m%d.%H%M%S).0-boot-$(git branch --show-current) GRUB="inst.repo=https://dl.rockylinux.org/pub/rocky/9/BaseOS/x86_64/os/" DNF_CONTENTDIR=true
```

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by lumarel** [comment]
Welp... time to run everything from 8.6 and 9.0

File: tests/os_release.pm [hunk 1]
```diff
@@ -78,21 +82,21 @@ sub run {
 
         # Test for Rocky Support Product
         $strip = strip_marks($content{'ROCKY_SUPPORT_PRODUCT'});
-        rec_log "ROCKY_SUPPORT_PRODUCT should be $name and is $strip", $strip eq $fullname, $failref;
+        if ( $ver_major = '9' ) {
+            $fullname = qq/$fullname $ver_major/;
+            $fullname =~ s/ /-/g;
+        }
+        rec_log "ROCKY_SUPPORT_PRODUCT should be $fullname and is $strip", $strip eq $fullname, $failref;
```
Comment (lumarel) [inline tests/os_release.pm:89]: This does not work for 8.

**Review by lumarel — APPROVED** [review]
I ran basically everything for 8.6 and 9.0 now, there are several failures, which are not blocking in my opinion, there is only the os_release check for 8.6 which is failing, I don't know if we want to handle that right now or just fix after merging this.

And please.. please don't squash merge this request so it will be far more easy to wrap our head around the changes when we later need to troubleshoot something of these.
Thank you!

**Review by StackKorora — APPROVED** [review]
